"""Add position column

Revision ID: a200ec63ecf0
Revises: c0eab4f9fef2
Create Date: 2026-01-17 14:47:46.108277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a200ec63ecf0'
down_revision: Union[str, Sequence[str], None] = 'c0eab4f9fef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'position')
    # ### end Alembic commands ###
